[note]
id-charset = "alphanum"
id-length = 8
id-case = "lower"
default-title = "untitled"
filename = "{{id}}"
extension = "md"
template = "default.md"

[format.markdown]
link-format = "markdown"
link-drop-extension = true
